[firebase]
type = "service_account"
project_id = "aircare-534c0"
private_key_id = "47693aa203f11f7f52c7116876dfeea021ee165e"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC/2QrYvvhURXWm
seoDndNvfY1mWPn4XBlOeHMfMN/K14J5Anyc0ZFhD98zIiuEQtHwoxZ9vnPGdh1w
GO7GEQSCsKgS6DwlN0Xg9Hwb0aRuIhI3gY06q2AtkjfFHfbYJ6ZQJbtSDYJOFpHV
TafEZqfntwnSh6JXfvIaLOWRsQHP2W235LHVfnI6cCIbwCVx8uGNGXKWEQVbnrT1
e/PznSPhK6p0pnK382tWzkch7Nkt5IaTAiD/HywAI8JRJWD6oWrovkKOjcSumKUt
whs6ke9VJyzGik89ONJ24/SXrN2/LnFoImWdpRCBLetA/rsfkoplH6+VcE588Zbe
qXGiaqJJAgMBAAECggEAA2hrbmfks7kwz/9nZ51f76I8fEhxVvg/2ip+lQZtEJvd
F/beLXpK3v1asCcCZzeOpiZ81EqpS38L99KhjzLR2zEgfdwn5rCsKkT9iBBPH5u1
qiHALKjLAmmPWbjgtSdDJ4z8CQbvZ8wJLCT/KW3PZr4pdlbCy1Nty97nTGa8tatL
BMvF33apTVMa0eZfTpf2AA+v9bmwPNqUYGB74lUPWeHC8ctm57wPZM7pzlWsHWdX
KLdDeOTdFTjMwiSzUzPv9JwXaXw5xFeS8omETfcftyhLmzfvBjlrlUnKzfBhPKdS
uwET/pCk7OSJsG2z9TFhPVsePuktVKe2olzgj37MpwKBgQDzQ3tN7gZhRi3VwUAt
Fq/t31xKrPRwLf1z/yjNEZ8/FPUR4nVFrSS54ItX7cbCTz6iyEx79gs6ik3XyYXR
kEemWYgctU1f33DJD4O2CsFvtl+ZXLV49pFTF3cUpTr8x74FqhiSN16+WuQDGZSZ
0OS5gm6tGsNXNHdc3l4VihplWwKBgQDJ5GxSXsHSI6GX0JSYYLM6Cq24u9pdRxrq
6uu0dyH9gzfquluJOTbAOWRCv2xlIygX5Uw8EmxPtIhn4pj4XZNPYQ8S/mJi2hNh
1FQgeNY/3Flie4+paxi3COwRAdV9yM6jAwTg2vAMiwwrmOgVmi1MoyKQyN3zUz4q
vO3h7pmUKwKBgQDjeS+9QJ3AqmJD5tC/GN7sPZhM0AxHNgoyROB/WkIiN9OupKdq
vyx/kARc9aCNpJJ6n3g91mbLl/aQmQZEX3lQiZoo1jSDOSp7KMHOIaKedthQTYv4
kAB2xZN5v8Q4CgObwmH1oEc9Ezrx1yLI7rhi7B/YSRVu30Xalqk91QU3zwKBgB95
be21eg/xoBqT2OachLRyv7yCBLvv/uFKuG5M+E6Wa1w7q1OMSN3U1K2XPCXUQkbf
Z3AiCyKt6WoQqHpn1DRW1EvIvrvcdZMVz/uz+uq/xmuVCcOGv7ahPHQ2TfsrGBPP
v63yU+QQtVgCoYPkolVFRXk+52Mswg9VntxPH0A7AoGAa+lceDc95MsyeGxNK1IV
9y3GtejZVyrg4qKhFCcdmmB7RIOqbJ4lUdpveIPHenkPTbP/kmyDbuScTPktLhvu
6E5wQPOWGlcdXypj6vo/Slzudi4+D8uEstKSmBWz2qBFcKltcd/tLgMHmhPzosWx
1A8zw3RwzAQEXPa2VBtugS0=
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@aircare-534c0.iam.gserviceaccount.com"
client_id = "100111012312647036103"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40aircare-534c0.iam.gserviceaccount.com"
universe_domain = "googleapis.com"